# Generated by Django 4.1.3 on 2022-11-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_client_mobile_operator_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileOperatorChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(verbose_name='Коды мобильных операторов')),
            ],
        ),
        migrations.RemoveField(
            model_name='mailing',
            name='operator_filter',
        ),
        migrations.AddField(
            model_name='mailing',
            name='operator_filter',
            field=models.ManyToManyField(to='mailing.mobileoperatorchoices', verbose_name='Фильтр клиентов по коду оператора'),
        ),
    ]
