# Generated by Django 4.1.3 on 2022-11-15 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_mobileoperatorchoices_remove_mailing_operator_filter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='operator_filter',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='mailing.mobileoperatorchoices', verbose_name='Фильтр клиентов по коду оператора'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='tag_filter',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Фильтр клиентов по тегу'),
        ),
    ]
