# Generated by Django 4.1.3 on 2022-11-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_operator_filter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileoperatorchoices',
            name='id',
        ),
        migrations.AlterField(
            model_name='mobileoperatorchoices',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Коды мобильных операторов'),
        ),
    ]
