# Generated by Django 4.1.3 on 2022-11-15 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_remove_mobileoperatorchoices_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='created',
        ),
        migrations.RemoveField(
            model_name='message',
            name='updated',
        ),
    ]
