version: "3.9"

services:
  redis:
    image: redis
    restart: always
  api:
    restart: always
    build:
      context: .
    image: yesha999/notification_service
    ports:
      - 8000:8000
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.docker_env:/app/.env
  migrations:
    build:
      context: .
    image: yesha999/notification_service
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.docker_env:/app/.env
    command: python manage.py migrate
  postgres:
    restart: always
    image: postgres:12.4-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: notification_service
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  worker:
    restart: always
    build:
      context: .
    volumes:
      - ./.docker_env:/app/.env
    command: celery --workdir=. -A notification_service worker
